import {
	chmod,
	copyFile,
	mkdir,
	readFile,
	rm,
	unlink,
	writeFile,
} from "node:fs/promises";
import { constants } from "node:fs";
import { basename, dirname, join } from "node:path";
import type { VmConfig } from "./config";
import { checked, CliError, Libvirt, run } from "./libvirt";

function quote(value: string): string {
	return `'${value.replaceAll("'", `'\\''`)}'`;
}

async function requirePath(path: string, description: string): Promise<void> {
	if (!(await Bun.file(path).exists()))
		throw new CliError(`${description} not found: ${path}`);
}

async function ensureSshKey(config: VmConfig): Promise<void> {
	const privateKey = config.publicKeyPath.replace(/\.pub$/, "");
	if (
		(await Bun.file(privateKey).exists()) &&
		(await Bun.file(config.publicKeyPath).exists())
	)
		return;
	await mkdir(dirname(privateKey), { recursive: true, mode: 0o700 });
	await checked([
		"ssh-keygen",
		"-q",
		"-t",
		"ed25519",
		"-N",
		"",
		"-f",
		privateKey,
		"-C",
		"vm-manager",
	]);
}

async function prepareArchiveCache(config: VmConfig): Promise<void> {
	const archiveDir = join(config.hostSharedDir, "apt-archives");
	await mkdir(join(archiveDir, "partial"), { recursive: true, mode: 0o777 });
	await chmod(archiveDir, 0o777);
	await chmod(join(archiveDir, "partial"), 0o777);
	const lock = join(archiveDir, "lock");
	await Bun.write(lock, "");
	await chmod(lock, 0o666);
}

async function ensureNetwork(config: VmConfig): Promise<void> {
	await checked(["virsh", "-c", config.uri, "net-autostart", config.network]);
	const info = await checked([
		"virsh",
		"-c",
		config.uri,
		"net-info",
		config.network,
	]);
	if (!/^Active:\s+yes$/m.test(info)) {
		await checked(["virsh", "-c", config.uri, "net-start", config.network]);
	}
	const xml = await checked([
		"virsh",
		"-c",
		config.uri,
		"net-dumpxml",
		config.network,
	]);
	const existingHost = xml.match(
		new RegExp(`<host[^>]*mac=['\"]${config.baseMac}['\"][^>]*/>`),
	)?.[0];
	if (
		existingHost &&
		!existingHost.includes(`ip='${config.baseIp}'`) &&
		!existingHost.includes(`ip=\"${config.baseIp}\"`)
	) {
		throw new CliError(
			`DHCP reservation conflict for ${config.baseMac}: ${existingHost}`,
		);
	}
	if (!existingHost) {
		await checked([
			"virsh",
			"-c",
			config.uri,
			"net-update",
			config.network,
			"add",
			"ip-dhcp-host",
			`<host mac='${config.baseMac}' ip='${config.baseIp}' name='debian13-kde'/>`,
			"--live",
			"--config",
		]);
	}
}

async function writePreseed(config: VmConfig, path: string): Promise<void> {
	const passwordHash = (
		await checked(["openssl", "passwd", "-6", config.password])
	).trim();
	const publicKey = (await readFile(config.publicKeyPath, "utf8")).trim();
	const content = `# Generated by vm. This file is removed when installation finishes.
d-i debian-installer/locale string en_US.UTF-8
d-i keyboard-configuration/xkb-keymap select us
d-i console-setup/ask_detect boolean false
d-i netcfg/choose_interface select auto
d-i netcfg/get_hostname string debian13-kde
d-i netcfg/get_domain string local
d-i netcfg/hostname string debian13-kde
d-i mirror/country string manual
d-i mirror/http/hostname string deb.debian.org
d-i mirror/http/directory string /debian
d-i mirror/http/proxy string
d-i mirror/suite string trixie
d-i mirror/udeb/suite string trixie
d-i apt-setup/use_mirror boolean true
d-i apt-setup/cdrom/set-first boolean false
d-i apt-setup/disable-cdrom-entries boolean true
d-i apt-setup/non-free-firmware boolean true
d-i passwd/root-login boolean false
d-i passwd/make-user boolean true
d-i passwd/user-fullname string Easydev
d-i passwd/username string ${config.user}
d-i passwd/user-password-crypted password ${passwordHash}
d-i passwd/user-default-groups string audio cdrom video sudo
d-i clock-setup/utc boolean true
d-i time/zone string Asia/Seoul
d-i clock-setup/ntp boolean true
d-i partman-auto/method string lvm
d-i partman-auto/disk string /dev/vda
d-i partman-lvm/device_remove_lvm boolean true
d-i partman-md/device_remove_md boolean true
d-i partman-lvm/confirm boolean true
d-i partman-lvm/confirm_nooverwrite boolean true
d-i partman-auto/choose_recipe select atomic
d-i partman-auto-lvm/guided_size string max
d-i partman-partitioning/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true
tasksel tasksel/first multiselect standard, kde-desktop, ssh-server
d-i shared/default-x-display-manager select sddm
d-i pkgsel/include string sudo,openssh-server,qemu-guest-agent,curl,ca-certificates,git,build-essential,pkg-config,libssl-dev,sqlite3,podman,podman-compose,uidmap,slirp4netns,fuse-overlayfs,dbus-user-session,wireguard-tools
d-i pkgsel/upgrade select safe-upgrade
d-i pkgsel/update-policy select unattended-upgrades
d-i grub-installer/only_debian boolean true
d-i grub-installer/with_other_os boolean true
d-i grub-installer/bootdev string /dev/vda
d-i preseed/late_command string in-target sh -c 'install -d -m 700 /home/${config.user}/.ssh; printf "%s\\n" "${publicKey}" > /home/${config.user}/.ssh/authorized_keys; chown -R ${config.user}:${config.user} /home/${config.user}/.ssh; chmod 600 /home/${config.user}/.ssh/authorized_keys; install -d -o ${config.user} -g ${config.user} -m 775 ${config.guestSharedDir}; printf "%s\\n" "${config.virtiofsTag} ${config.guestSharedDir} virtiofs defaults,nofail,x-systemd.automount 0 0" >> /etc/fstab; systemctl enable qemu-guest-agent ssh'
d-i finish-install/reboot_in_progress note
`;
	await writeFile(path, content, { mode: 0o600 });
}

async function installDomain(config: VmConfig): Promise<void> {
	await requirePath(config.isoPath, "Debian ISO");
	await requirePath(config.publicKeyPath, "SSH public key");
	await mkdir(config.imagesDir, { recursive: true });
	const preseed = join(
		process.env.XDG_RUNTIME_DIR ?? "/tmp",
		`${config.name}-preseed-${process.pid}.cfg`,
	);
	await writePreseed(config, preseed);
	try {
		const exitCode = await run(
			[
				"virt-install",
				"--connect",
				config.uri,
				"--name",
				config.name,
				"--memory",
				String(config.memoryMiB),
				"--vcpus",
				String(config.vcpus),
				"--cpu",
				"host-passthrough",
				"--memorybacking",
				"access.mode=shared",
				"--disk",
				`path=${config.diskPath},size=${config.diskGiB},format=qcow2,bus=virtio`,
				"--filesystem",
				`source=${config.hostSharedDir},target=${config.virtiofsTag},driver.type=virtiofs,accessmode=passthrough`,
				"--os-variant",
				"debian13",
				"--network",
				`network=${config.network},model=virtio,mac=${config.baseMac}`,
				"--graphics",
				"spice",
				"--video",
				"virtio",
				"--channel",
				"unix,target_type=virtio,name=org.qemu.guest_agent.0",
				"--location",
				config.isoPath,
				"--initrd-inject",
				preseed,
				"--extra-args",
				`auto=true priority=critical preseed/file=/${basename(preseed)}`,
				"--noautoconsole",
				"--wait",
				"-1",
			],
			true,
		);
		if (exitCode.exitCode !== 0)
			throw new CliError("Debian installation failed", exitCode.exitCode);
	} finally {
		await rm(preseed, { force: true });
	}
}

async function ensureDomainDevices(
	config: VmConfig,
	libvirt: Libvirt,
): Promise<void> {
	let xml = await checked([
		"virsh",
		"-c",
		config.uri,
		"dumpxml",
		"--inactive",
		config.name,
	]);
	let changed = false;
	if (!/<access mode=['"]shared['"]/.test(xml)) {
		xml = xml.replace(
			"</currentMemory>",
			"</currentMemory>\n  <memoryBacking>\n    <access mode='shared'/>\n  </memoryBacking>",
		);
		changed = true;
	}
	if (
		!xml.includes(`<target dir='${config.virtiofsTag}'`) &&
		!xml.includes(`<target dir="${config.virtiofsTag}"`)
	) {
		xml = xml.replace(
			"</devices>",
			`    <filesystem type='mount' accessmode='passthrough'>\n      <driver type='virtiofs'/>\n      <source dir='${config.hostSharedDir}'/>\n      <target dir='${config.virtiofsTag}'/>\n    </filesystem>\n  </devices>`,
		);
		changed = true;
	}
	if (!changed) return;
	await libvirt.shutdown(config.name);
	const path = join(
		process.env.XDG_RUNTIME_DIR ?? "/tmp",
		`${config.name}-domain-${process.pid}.xml`,
	);
	try {
		await writeFile(path, xml, { mode: 0o600 });
		await checked(["xmllint", "--noout", path]);
		await checked(["virsh", "-c", config.uri, "define", path]);
	} finally {
		await rm(path, { force: true });
	}
}

async function configureGuestFiles(
	config: VmConfig,
	libvirt: Libvirt,
): Promise<void> {
	const home = `/home/${config.user}`;
	const marker = `host-to-guest-${Date.now()}`;
	const publicKey = (await readFile(config.publicKeyPath, "utf8")).trim();
	const script = `set -eu
printf '%s:%s\\n' ${quote(config.user)} ${quote(config.password)} | chpasswd
install -d -o ${config.user} -g ${config.user} -m 700 ${home}/.ssh
touch ${home}/.ssh/authorized_keys
grep -qxF ${quote(publicKey)} ${home}/.ssh/authorized_keys || printf '%s\\n' ${quote(publicKey)} >> ${home}/.ssh/authorized_keys
chown -R ${config.user}:${config.user} ${home}/.ssh
chmod 600 ${home}/.ssh/authorized_keys
install -d -o ${quote(config.user)} -g ${quote(config.user)} -m 775 ${quote(config.guestSharedDir)}
sed -i '\\|[[:space:]]${config.guestSharedDir}[[:space:]]|d' /etc/fstab
printf '%s\\n' ${quote(`${config.virtiofsTag} ${config.guestSharedDir} virtiofs defaults,nofail,x-systemd.automount 0 0`)} >> /etc/fstab
systemctl daemon-reload
mountpoint -q ${quote(config.guestSharedDir)} || mount ${quote(config.guestSharedDir)}
chown ${quote(`${config.user}:${config.user}`)} ${quote(config.guestSharedDir)}
rm -f /etc/apt/apt.conf.d/00host-cache
cat > /etc/apt/apt.conf.d/00shared-archives <<'EOF'
Dir::Cache::archives "${config.guestSharedDir}/apt-archives";
EOF
systemctl enable --now ssh qemu-guest-agent
test -d ${quote(home)}
podman --version
wg --version`;
	const output = await libvirt.guestChecked(config.name, script);
	if (output.trim()) console.log(output.trim());
	await Bun.write(
		join(config.hostSharedDir, "host-to-guest.txt"),
		`${marker}\n`,
	);
	await libvirt.guestChecked(
		config.name,
		`set -eu
test "$(cat ${quote(join(config.guestSharedDir, "host-to-guest.txt"))})" = ${quote(marker)}
runuser -u ${quote(config.user)} -- sh -c ${quote(`printf '%s\\n' guest-to-host > ${join(config.guestSharedDir, "guest-to-host.txt")}`)}`,
	);
}

async function plasmaVersion(
	config: VmConfig,
	libvirt: Libvirt,
): Promise<string> {
	const output = await libvirt.guestChecked(
		config.name,
		"dpkg-query -W -f='${Version}' plasma-desktop",
	);
	return output.match(/(\d+\.\d+\.\d+)/)?.[1] ?? "6";
}

async function initializePlasma(
	config: VmConfig,
	libvirt: Libvirt,
): Promise<void> {
	const marker = "/var/lib/vm-tool/plasma-initialized";
	const existing = await libvirt.guestExec(config.name, `test -f ${marker}`);
	const version = await plasmaVersion(config, libvirt);
	const home = `/home/${config.user}`;
	await libvirt.guestChecked(
		config.name,
		`set -eu
install -d -m 755 /etc/xdg/kded6
cat > /etc/xdg/kded6/plasma-welcome <<'EOF'
[General]
autoload=false
EOF
install -d -o ${config.user} -g ${config.user} -m 700 ${home}/.config ${home}/.cache
cat > ${home}/.config/plasma-welcomerc <<'EOF'
[General]
LastSeenVersion=${version}
ShowUpdatePage=false
EOF
cat > ${home}/.config/ksmserverrc <<'EOF'
[General]
loginMode=emptySession
EOF
chown ${config.user}:${config.user} ${home}/.config/plasma-welcomerc ${home}/.config/ksmserverrc`,
	);
	if (existing.exitCode === 0) return;

	console.log("[vm] initializing the first Plasma session");
	await libvirt.guestChecked(
		config.name,
		`set -eu
install -d -m 755 /etc/sddm.conf.d
cat > /etc/sddm.conf.d/99-vm-initialize.conf <<'EOF'
[Autologin]
User=${config.user}
Session=plasma.desktop
Relogin=false
EOF
loginctl terminate-user ${config.user} 2>/dev/null || true
systemctl restart sddm`,
	);
	let started = false;
	for (let attempt = 0; attempt < 90; attempt++) {
		const result = await libvirt.guestExec(
			config.name,
			`pgrep -u ${config.user} -x plasmashell >/dev/null`,
		);
		if (result.exitCode === 0) {
			started = true;
			break;
		}
		await Bun.sleep(2000);
	}
	if (!started) throw new CliError("Plasma first-login session did not start");
	await Bun.sleep(45000);
	await libvirt.guestChecked(
		config.name,
		`set -eu
runuser -u ${config.user} -- env HOME=${home} kbuildsycoca6 --noincremental >/dev/null 2>&1 || true
runuser -u ${config.user} -- env HOME=${home} fc-cache -f >/dev/null 2>&1 || true
rm -f /etc/sddm.conf.d/99-vm-initialize.conf
install -d -m 755 /var/lib/vm-tool
touch ${marker}
loginctl terminate-user ${config.user} 2>/dev/null || true
systemctl restart sddm`,
	);
	console.log("[vm] Plasma first-login initialization completed");
}

export async function setupDebian(
	config: VmConfig,
	reinstall = false,
): Promise<void> {
	const libvirt = new Libvirt(config);
	await ensureSshKey(config);
	await requirePath(config.isoPath, "Debian ISO");
	await requirePath(config.publicKeyPath, "SSH public key");
	await mkdir(config.hostSharedDir, { recursive: true, mode: 0o770 });
	await prepareArchiveCache(config);
	await ensureNetwork(config);
	if (reinstall && (await libvirt.exists(config.name))) {
		console.log(`[vm] deleting ${config.name} for clean reinstall`);
		const actualDisk = await libvirt.diskPath(config.name);
		await libvirt.shutdown(config.name);
		await checked(["virsh", "-c", config.uri, "undefine", config.name]);
		await rm(actualDisk ?? config.diskPath, { force: true });
	}
	if (!(await libvirt.exists(config.name))) await installDomain(config);
	await ensureDomainDevices(config, libvirt);
	await checked(["virsh", "-c", config.uri, "autostart", config.name]);
	await libvirt.start(config.name);
	await libvirt.waitForAgent(config.name);
	await configureGuestFiles(config, libvirt);
	await initializePlasma(config, libvirt);
}

export async function createGolden(config: VmConfig): Promise<void> {
	const libvirt = new Libvirt(config);
	await ensureSshKey(config);
	if (!(await libvirt.exists(config.name)))
		throw new CliError(`Base VM does not exist: ${config.name}`);
	await libvirt.start(config.name);
	await libvirt.waitForAgent(config.name);
	await configureGuestFiles(config, libvirt);
	await initializePlasma(config, libvirt);
	await libvirt.shutdown(config.name);
	await rm(config.goldenPath, { force: true });
	await checked([
		"virsh",
		"-c",
		config.uri,
		"vol-download",
		"--pool",
		config.storagePool,
		basename(config.diskPath),
		config.goldenPath,
		"--sparse",
	]);
	await chmod(config.goldenPath, 0o444);
	await libvirt.start(config.name);
	console.log(`[vm] golden image: ${config.goldenPath}`);
}

export async function cloneDebian(
	baseConfig: VmConfig,
	cloneName: string,
): Promise<void> {
	await ensureSshKey(baseConfig);
	if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(cloneName))
		throw new CliError(`Invalid VM name: ${cloneName}`);
	await requirePath(baseConfig.goldenPath, "Golden image");
	const config = {
		...baseConfig,
		name: cloneName,
		diskPath: join(baseConfig.imagesDir, `${cloneName}.qcow2`),
	};
	const libvirt = new Libvirt(config);
	if (await libvirt.exists(cloneName))
		throw new CliError(`Domain already exists: ${cloneName}`);
	if (await Bun.file(config.diskPath).exists())
		throw new CliError(`Disk already exists: ${config.diskPath}`);
	await prepareArchiveCache(config);
	await copyFile(
		config.goldenPath,
		config.diskPath,
		constants.COPYFILE_FICLONE_FORCE,
	);
	await chmod(config.diskPath, 0o600);
	await checked([
		"virsh",
		"-c",
		config.uri,
		"pool-refresh",
		config.storagePool,
	]);
	const result = await run(
		[
			"virt-install",
			"--connect",
			config.uri,
			"--name",
			cloneName,
			"--memory",
			String(config.memoryMiB),
			"--vcpus",
			String(config.vcpus),
			"--cpu",
			"host-passthrough",
			"--memorybacking",
			"access.mode=shared",
			"--disk",
			`path=${config.diskPath},format=qcow2,bus=virtio`,
			"--filesystem",
			`source=${config.hostSharedDir},target=${config.virtiofsTag},driver.type=virtiofs,accessmode=passthrough`,
			"--os-variant",
			"debian13",
			"--network",
			`network=${config.network},model=virtio`,
			"--graphics",
			"spice",
			"--video",
			"virtio",
			"--channel",
			"unix,target_type=virtio,name=org.qemu.guest_agent.0",
			"--import",
			"--autostart",
			"--noautoconsole",
		],
		true,
	);
	if (result.exitCode !== 0)
		throw new CliError("Clone domain creation failed", result.exitCode);
	await libvirt.waitForAgent(cloneName);
	await libvirt.guestChecked(
		cloneName,
		`set -eu
hostnamectl hostname ${quote(cloneName)}
rm -f /etc/ssh/ssh_host_*
ssh-keygen -A
rm -f /var/lib/dbus/machine-id
truncate -s 0 /etc/machine-id
systemd-machine-id-setup
systemctl restart ssh`,
	);
	await configureGuestFiles(config, libvirt);
	await initializePlasma(config, libvirt);
}

export async function prepareCache(config: VmConfig): Promise<void> {
	await mkdir(config.hostSharedDir, { recursive: true, mode: 0o770 });
	await prepareArchiveCache(config);
	console.log(
		`[vm] shared APT cache: ${join(config.hostSharedDir, "apt-archives")}`,
	);
}
